In [5]:
#1. Create a NumPy array with values from 10 to 49 (inclusive).
#● Reshape it into a 4x10 matrix.
#● Then extract the last column from the reshaped matrix
import numpy as np
arr = np.arange(10,50)
print("Array: ", arr)
print()
arr2 = arr.reshape(4,10)
print("Reshaped: ",arr2)
print()
last_column = arr2[:, -1]
print("Last Column:", last_column)

Array:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Reshaped:  [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

Last Column: [19 29 39 49]


In [26]:
#2. Create two 3×3 matrices:
#One filled with all 5s , One with values from 1 to 9
arr = np.full((3,3),5)
matrix = np.arange(1,10)
arr2 = matrix.reshape(3,3)
print(arr)
print()
print(arr2)
print()
#● Add the two matrices
sum = arr+arr2
print("The sum is")
print(f"={sum}")
#● Multiply them element-wise
product = arr*arr2
print("The product is")
print(product)
print()
#● Then find the transpose of the result
arr_matrix = product.T
print("The transpose of the result")
print(arr_matrix)

[[5 5 5]
 [5 5 5]
 [5 5 5]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

The sum is
=[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
The product is
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

The transpose of the result
[[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [40]:
#3. Create a NumPy array of 15 random integers between 10 and 100.
arr = np.random.randint(10, 101, 15)
print("Original Array:", arr)
print()
#● Replace all values greater than 50 with -1
replaced_count = np.sum(arr > 50)
#● Count how many values were replaced.
arr[arr > 50] = -1
print("Modified Array:")
print(arr)
print()
print(f"Number of values replaced: {replaced_count}")

Original Array: [52 71 41 15 83 21 24 99 56 32 67 47 95 59 90]

Modified Array:
[-1 -1 41 15 -1 21 24 -1 -1 32 -1 47 -1 -1 -1]

Number of values replaced: 9


In [58]:
#4. Generate a 5×4 array with random values between 0 and 1 (float).
matrix = np.random.rand(5, 4)
print("5x4 Matrix:")
print(matrix)
print()
#● Find the row with the maximum sum of values.
row_sums = np.sum(matrix, axis=1)
max_row_index = np.argmax(row_sums)
print(row_sums)
print("The row index with the maximum sum is:", max_row_index)
print()
#● Normalize each row using the formula:
mins = matrix.min(axis=1, keepdims=True)
maxs = matrix.max(axis=1, keepdims=True)
normalized_matrix = (matrix - mins) / (maxs - mins)
print("Normalized Matrix")
print(normalized_matrix)

5x4 Matrix:
[[0.53142574 0.00426246 0.8144101  0.86043003]
 [0.24836377 0.72837657 0.85450162 0.27390205]
 [0.10175904 0.26234274 0.04564909 0.62389799]
 [0.05596394 0.01902248 0.47931217 0.77653659]
 [0.56865931 0.19398338 0.61635374 0.10093766]]

[2.21052834 2.10514401 1.03364886 1.33083519 1.47993409]
The row index with the maximum sum is: 0

Normalized Matrix
[[0.61572441 0.         0.94624892 1.        ]
 [0.         0.79192019 1.         0.0421328 ]
 [0.09703425 0.37474114 0.         1.        ]
 [0.04876669 0.         0.60763184 1.        ]
 [0.90746423 0.18052546 1.         0.        ]]


In [67]:
#5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
#● Find all unique elements
unq = np.unique(arr)
print(unq)
#● Find the duplicates (elements that appear more than once)
values, counts = np.unique(arr, return_counts=True)
dups = values[counts > 1]
print("The duplicate elements are",dups)

[1 3 5 7 9]
The duplicate elements are [1 3 5]


In [75]:
#6. Create a 6×6 NumPy array with values from 1 to 36.
ar = np.arange(1,37)
arr = ar.reshape(6,6)
#● Extract the middle 4×4 submatrix.
submatrix = arr[1:5,1:5]
print("The submatrix is")
print(submatrix)
print()
#● Then extract all even numbers from this submatrix.
even_numbers = submatrix[submatrix % 2 == 0]
print("The even numbers from the submatrix are:")
print(even_numbers)

The submatrix is
[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

The even numbers from the submatrix are:
[ 8 10 14 16 20 22 26 28]


In [83]:
#7. Generate an array of shape (3, 4) with values from 0 to 11.
ar = np.arange(0,12)
arr = ar.reshape(3,4)
print("Array:")
print(arr)
print()
#● Reshape it to (2, 6)
reshaped = arr.reshape(2,6)
print("The reshaped array")
print(reshaped)
print()
#● Then flatten it into a 1D array
flattened = reshaped.flatten()
print("The flattened into 1D array",flattened)
print()
#● Convert the 1D array back to shape (4, 3)
arr_re = flattened.reshape(3,4)
print("The 1D array back to shape (4, 3)")
print(arr_re)

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

The reshaped array
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

The flattened into 1D array [ 0  1  2  3  4  5  6  7  8  9 10 11]

The 1D array back to shape (4, 3)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [92]:
#8. Create an array: a = np.array([[1, 2], [3, 4]])
a = np.array([[1, 2], [3, 4]])
print("The array is \n",a)
#● Append a new row [5, 6]
arr = np.array([[5,6]])
appended = np.append(a,arr,axis=0)
print(appended)
print()
#● Then append a new column [7, 8, 9]
arr2 = np.array([[7],
                 [8],
                 [9]])
appended2 = np.hstack((appended,arr2))
print(appended2)

The array is 
 [[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]

[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [102]:
#a = np.array([1, 2, 3])
#b = np.array([4, 5, 6])
#c = np.array([7, 8, 9])
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
#● Join them into a single array
joined_array = np.concatenate((a, b, c))
print("Join them into a single array",joined_array)
print()
#● Reshape the result into a 3×3 matrix
reshaped = joined_array.reshape(3,3)
print("Reshape the result into a 3×3 matrix: \n",reshaped)
print()
#● Extract the diagonal elements
diag = np.diag(reshaped)
print("Extract the diagonal elements:",diag)

Join them into a single array [1 2 3 4 5 6 7 8 9]

Reshape the result into a 3×3 matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Extract the diagonal elements: [1 5 9]


In [109]:
#10. Create a NumPy array of integers from 1 to 20.
arr = np.arange(1,20)
#● Extract all values that are divisible by 3 or 5.
result = arr[(arr%3 ==0) | (arr%5 ==0)]
print("All values that are divisible by 3 or 5:",result)
#● Count how many such values exist.
count = len(result)
print("The number of values:",count)

All values that are divisible by 3 or 5: [ 3  5  6  9 10 12 15 18]
The number of values: 8
